### ISSUE TITLE
Maven repo is down

### ISSUE THREAD

**Issue by jonneves** [upcrob/spring-batch-sort-merge#2]
Stumble across an old project that uses your amazing lib.
Unfortunately is breaking cause https://dl.bintray.com/upcrob/maven/ is out.

Any plans to release in a different maven repo?

**Comment by upcrob** [comment]
Try using this package:
```
<dependency>
  <groupId>com.upcrob.spring.batch</groupId>
  <artifactId>spring-batch-sort-merge</artifactId>
  <version>1.0</version>
</dependency> 
```
As a side note, is the old project that uses it public?  If so, I'd love to hear out of personal curiosity where/how this is being used in the wild (if you don't mind sharing, of course).

**Comment by jonneves** [comment]
Hey Rob,
Thanks for the fast response.
That is the dependency that we are using, but it's failing to download (
https://dl.bintray.com/upcrob/maven/com/upcrob/spring/batch/spring-batch-sort-merge/1.0/spring-batch-sort-merge-1.0.pom
is forbiden)

Not sure if your server is still available for us to use, or if it's not
anymore, maybe I need to add another repository to find the package.

About the solution, it was from a startup that would collect receipt data
from retailers and check their coupon and discount code usages in the
platform.
The product was unfortunately discontinued for the public but the receipt
parsing is still used internally, so we use your lib to sort the tlog files.

Best,
Jon

**Comment by upcrob** [comment]
Sorry about that.  I attempted to create a GitHub package earlier this morning (since Bintray is no more), but failed to include the repository URL.  Unfortunately, it looks like the GitHub package system doesn't support unauthorized downloads yet, so that probably wouldn't have been very helpful, regardless.

I drafted a new release for the project with the old binaries that were in Bintray, here: https://github.com/upcrob/spring-batch-sort-merge/releases/tag/1.0

You should be able to add them manually to your local artifact repository or project.  It's not ideal, but that may help you solve your immediate problem.

**Comment by jonneves** [comment]
Awesome, thanks!
Jon
